export const PERMISSIONS = [
  { key: 'users.view', resource: 'users', action: 'view', description: 'View users' },
  { key: 'users.create', resource: 'users', action: 'create', description: 'Create users' },
  { key: 'users.update', resource: 'users', action: 'update', description: 'Update users' },
  { key: 'users.delete', resource: 'users', action: 'delete', description: 'Delete users' },
  { key: 'roles.view', resource: 'roles', action: 'view', description: 'View roles' },
  { key: 'roles.create', resource: 'roles', action: 'create', description: 'Create roles' },
  { key: 'roles.update', resource: 'roles', action: 'update', description: 'Update roles' },
  { key: 'roles.delete', resource: 'roles', action: 'delete', description: 'Delete roles' },
  { key: 'roles.assign', resource: 'roles', action: 'assign', description: 'Assign roles to users' },
  {
    key: 'permissions.view',
    resource: 'permissions',
    action: 'view',
    description: 'View permissions',
  },
  {
    key: 'departments.view',
    resource: 'departments',
    action: 'view',
    description: 'View departments',
  },
  {
    key: 'departments.create',
    resource: 'departments',
    action: 'create',
    description: 'Create departments',
  },
  {
    key: 'departments.update',
    resource: 'departments',
    action: 'update',
    description: 'Update departments',
  },
  {
    key: 'departments.delete',
    resource: 'departments',
    action: 'delete',
    description: 'Delete departments',
  },
  { key: 'positions.view', resource: 'positions', action: 'view', description: 'View positions' },
  {
    key: 'positions.create',
    resource: 'positions',
    action: 'create',
    description: 'Create positions',
  },
  {
    key: 'positions.update',
    resource: 'positions',
    action: 'update',
    description: 'Update positions',
  },
  {
    key: 'positions.delete',
    resource: 'positions',
    action: 'delete',
    description: 'Delete positions',
  },
  { key: 'employees.view', resource: 'employees', action: 'view', description: 'View employees' },
  {
    key: 'employees.create',
    resource: 'employees',
    action: 'create',
    description: 'Create employees',
  },
  {
    key: 'employees.update',
    resource: 'employees',
    action: 'update',
    description: 'Update employees',
  },
  {
    key: 'employees.delete',
    resource: 'employees',
    action: 'delete',
    description: 'Delete employees',
  },
  {
    key: 'employees.view_salary',
    resource: 'employees',
    action: 'view_salary',
    description: 'View employee salary information',
  },
  {
    key: 'audit-logs.view',
    resource: 'audit-logs',
    action: 'view',
    description: 'View audit logs',
  },
  { key: 'media.view', resource: 'media', action: 'view', description: 'View media library' },
  { key: 'media.create', resource: 'media', action: 'create', description: 'Upload and create media' },
  { key: 'media.update', resource: 'media', action: 'update', description: 'Update and move media' },
  { key: 'media.delete', resource: 'media', action: 'delete', description: 'Delete media' },
  { key: 'products.view', resource: 'products', action: 'view', description: 'View products' },
  { key: 'products.create', resource: 'products', action: 'create', description: 'Create products' },
  { key: 'products.update', resource: 'products', action: 'update', description: 'Update products' },
  { key: 'products.delete', resource: 'products', action: 'delete', description: 'Delete products' },
  { key: 'suppliers.view', resource: 'suppliers', action: 'view', description: 'View suppliers' },
  { key: 'suppliers.create', resource: 'suppliers', action: 'create', description: 'Create suppliers' },
  { key: 'suppliers.update', resource: 'suppliers', action: 'update', description: 'Update suppliers' },
  { key: 'suppliers.delete', resource: 'suppliers', action: 'delete', description: 'Delete suppliers' },
  { key: 'warehouses.view', resource: 'warehouses', action: 'view', description: 'View warehouses' },
  { key: 'warehouses.create', resource: 'warehouses', action: 'create', description: 'Create warehouses' },
  { key: 'warehouses.update', resource: 'warehouses', action: 'update', description: 'Update warehouses' },
  { key: 'warehouses.delete', resource: 'warehouses', action: 'delete', description: 'Delete warehouses' },
  { key: 'inventory.view', resource: 'inventory', action: 'view', description: 'View stock levels' },
  { key: 'inventory.adjust', resource: 'inventory', action: 'adjust', description: 'Adjust stock manually' },
  { key: 'purchasing.view', resource: 'purchasing', action: 'view', description: 'View purchase orders' },
  { key: 'purchasing.create', resource: 'purchasing', action: 'create', description: 'Create purchase orders' },
  { key: 'purchasing.update', resource: 'purchasing', action: 'update', description: 'Update purchase orders' },
  { key: 'purchasing.receive', resource: 'purchasing', action: 'receive', description: 'Receive goods from purchase orders' },
  {
    key: 'requisitions.view',
    resource: 'requisitions',
    action: 'view',
    description: 'View purchase requisitions',
  },
  {
    key: 'requisitions.create',
    resource: 'requisitions',
    action: 'create',
    description: 'Create purchase requisitions',
  },
  {
    key: 'requisitions.update',
    resource: 'requisitions',
    action: 'update',
    description: 'Update / submit / cancel purchase requisitions',
  },
  {
    key: 'requisitions.approve',
    resource: 'requisitions',
    action: 'approve',
    description: 'Approve or reject purchase requisitions',
  },
] as const;

export type PermissionKey = (typeof PERMISSIONS)[number]['key'];

export const SUPER_ADMIN_ROLE = 'Super Admin';
